src/main/java/org/neylson/videolocadora/managedbeans/AtoresBean.java
package org.neylson.videolocadora.managedbeans;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import org.neylson.videolocadora.entidades.Ator;
import org.neylson.videolocadora.infra.MessagesHelper;
import org.neylson.videolocadora.services.AtorService;

@Named
@ViewScoped
public class AtoresBean implements Serializable {
	
	private static final long serialVersionUID = -735873575521969041L;

	private Ator ator;
	@Inject
	private transient MessagesHelper mensagens;
	@Inject
	private transient AtorService atorService;
	private boolean editar = false;
	private List<Ator> atoresFiltrados;

	
	public List<Ator> getAll() {
		return atorService.list(); 
	}
	
	@Transactional
	public void remover(Long id) {
		Ator ator = atorService.buscar(id);
		atorService.remover(ator);

		mensagens.addMessage(new FacesMessage(FacesMessage.SEVERITY_INFO,
				"Ator removido com sucesso!", null));
	}

	@Transactional
	public void salvar() {
		atorService.salvar(ator);

		mensagens.addMessage(new FacesMessage("Ator cadastrado com sucesso!"));
		limpar();
	}
	
	public void limpar() {
		ator = new Ator();
	}
	
	public void carregar(Long id) {
		ator = atorService.buscar(id);
		setEditar(true);
	}

	@Transactional
	public void atualizar() {
		atorService.atualizar(ator);
		setEditar(false);
	}
	
	public Ator getAtor() {
		return ator;
	}

	public void setAtor(Ator ator) {
		this.ator = ator;
	}

	public boolean getEditar() {
		return editar;
	}

	public void setEditar(boolean editar) {
		this.editar = editar;
	}

	public List<Ator> getAtoresFiltrados() {
		return atoresFiltrados;
	}

	public void setAtoresFiltrados(List<Ator> atoresFiltrados) {
		this.atoresFiltrados = atoresFiltrados;
	}
	
	public List<Ator> completaAtores(String prefixo){
		return atorService.filter(prefixo);
	}
}

src/main/java/org/neylson/videolocadora/managedbeans/CategoriaBean.java
package org.neylson.videolocadora.managedbeans;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import org.neylson.videolocadora.entidades.Categoria;
import org.neylson.videolocadora.entidades.Categoria.Tipo;
import org.neylson.videolocadora.infra.MessagesHelper;
import org.neylson.videolocadora.services.CategoriaService;

@Named
@ViewScoped
public class CategoriaBean implements Serializable {


	private static final long serialVersionUID = -4932573275796631963L;
	@Inject
	private transient MessagesHelper mensagens;
	@Inject
	private transient CategoriaService categoriaService;
	private Categoria categoria = new Categoria();
	private boolean editar = false;

	
	public List<Categoria> getAll() {
		return categoriaService.list();
	}

	@Transactional
	public void remover(Long id) {
		Categoria categoria = categoriaService.buscar(id);
		categoriaService.remover(categoria);

		mensagens.addMessage(new FacesMessage(FacesMessage.SEVERITY_INFO,
				"Categoria removida com sucesso!", null));
	}

	@Transactional
	public void salvar() {
		categoriaService.salvar(categoria);

		mensagens.addMessage(new FacesMessage("Categoria cadastrada com sucesso!"));
		limpar();
	}

	public void limpar() {
		categoria = new Categoria();		
	}

	public void carregar(Long id) {
		categoria = categoriaService.buscar(id);
		setEditar(true);
	}

	@Transactional
	public void atualizar() {
		categoriaService.atualizar(categoria);
		setEditar(false);
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public boolean getEditar() {
		return editar;
	}

	public void setEditar(boolean editar) {
		this.editar = editar;
	}
	
	public SelectItem[] getTipos(){
		
		SelectItem[] items = new SelectItem[Categoria.Tipo.values().length];
		
		int i = 0;
		for (Tipo tipo : Categoria.Tipo.values()) {
			items[i++]= new SelectItem(tipo, tipo.name());
		}
		
		return items;
	}

}

src/main/webapp/funcionario/gerenciarAtores.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">

			<p:panel header="Atores Cadastrados">

				<p:commandButton value="Cadastrar Atores"
					action="#{atoresBean.limpar()}" update="ator-form"
					oncomplete="PF('panel-ator-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />

				<p:dataTable id="ator-datatable" var="ator"
					value="#{atoresBean.all}"
					filteredValue="#{atoresBean.atoresFiltrados}"
					emptyMessage="Nenhum registro encontrado.">

					<p:column filterBy="#{ator.nome}" headerText="Nome">
						<h:outputText value="#{ator.nome}" />
					</p:column>

					<p:column headerText="Qntd. de Oscars">
						<h:outputText value="#{ator.quantidadeDeOscars}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{atoresBean.remover(ator.id)}" update="ator-datatable" />

						<p:commandButton value="Editar"
							action="#{atoresBean.carregar(ator.id)}"
							oncomplete="PF('panel-ator-form').show();" update="ator-form" />
					</p:column>

				</p:dataTable>

			</p:panel>
		</h:form>

		<p:panel header="Dados do ator" widgetVar="panel-ator-form"
			visible="false" closable="true">

			<h:form prependId="false" id="ator-form">

				<p:panel>
					<p:panelGrid columns="2" styleClass="grid"
						columnClasses="label,value">

						<h:outputText value="Nome *" />
						<p:inputText label="Nome" value="#{atoresBean.ator.nome}" />

						<h:outputText value="Qntd. de Oscars: *" />
						<p:spinner value="#{atoresBean.ator.quantidadeDeOscars}" min="0"
							max="10" />

					</p:panelGrid>
				</p:panel>

				<p:panel>
					<p:commandButton value="Cadastrar" action="#{atoresBean.salvar}"
						update="ator-datatable,ator-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-ator-form');" icon="ui-icon-circle-plus" rendered="#{!atoresBean.editar}" />

					<p:commandButton value="Atualizar" action="#{atoresBean.atualizar}"
						update="ator-datatable,ator-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-ator-form');"
						icon="ui-icon-circle-plus" rendered="#{atoresBean.editar}" />
				</p:panel>
			</h:form>
		</p:panel>

	</ui:define>
</ui:composition>
</html>

src/main/webapp/funcionario/gerenciarCategorias.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">

			<p:panel header="Categorias Cadastradas">

				<p:commandButton value="Cadastrar categorias"
					action="#{categoriaBean.limpar()}" update="categoria-form"
					oncomplete="PF('panel-categoria-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />

				<p:dataTable id="categoria-datatable" var="categoria"
					value="#{categoriaBean.all}"
					emptyMessage="Nenhum registro encontrado.">

					<p:column headerText="Tipo">
						<h:outputText value="#{categoria.tipo}" />
					</p:column>

					<p:column headerText="Valor">
						<h:outputText value="#{categoria.valor}" />
					</p:column>

					<p:column headerText="Dias de locação">
						<h:outputText value="#{categoria.diasDeLocacao}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{categoriaBean.remover(categoria.id)}"
							update="categoria-datatable" />

						<p:commandButton value="Editar"
							action="#{categoriaBean.carregar(categoria.id)}"
							oncomplete="PF('panel-categoria-form').show();"
							update="categoria-form" />
					</p:column>

				</p:dataTable>


			</p:panel>
		</h:form>

		<p:panel header="Dados da Categoria" widgetVar="panel-categoria-form"
			closable="true" visible="false">

			<h:form prependId="false" id="categoria-form">

				<p:panel>
					<p:panelGrid columns="2" columnClasses="label,value"
						styleClass="grid">

						<h:outputText value="Tipo: " />
						<p:selectOneRadio value="#{categoriaBean.categoria.tipo}">
							<f:selectItems value="#{categoriaBean.tipos}" var="tipo"
								itemLabel="#{tipo}" itemValue="#{tipo}" />
						</p:selectOneRadio>

						<h:outputText value="Valor: " />
						<p:inputText value="#{categoriaBean.categoria.valor}" />

						<h:outputText value="Dias de locação: " />
						<p:spinner min="0"
							value="#{categoriaBean.categoria.diasDeLocacao}" />
					</p:panelGrid>
				</p:panel>
				<p:panel>

					<p:commandButton value="Cadastrar"
						action="#{categoriaBean.salvar()}"
						update="categoria-datatable,categoria-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-categoria-form');"
						icon="ui-icon-circle-plus" rendered="#{!categoriaBean.editar}" />

					<p:commandButton value="Atualizar"
						action="#{categoriaBean.atualizar()}"
						update="categoria-datatable,categoria-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-categoria-form');"
						icon="ui-icon-circle-plus" rendered="#{categoriaBean.editar}" />
				</p:panel>
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/funcionario/gerenciarClientes.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">

			<p:panel header="Clientes Cadastrados">

				<p:commandButton value="Cadastrar cliente"
					action="#{clientesBean.limpar()}" update="cliente-form"
					oncomplete="PF('panel-cliente-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />

				<p:dataTable id="cliente-datatable" var="cliente"
					value="#{clientesBean.all}"
					emptyMessage="Nenhum registro encontrado.">


					<p:column headerText="Nome">
						<h:outputText value="#{cliente.nome}" />
					</p:column>

					<p:column headerText="CPF">
						<h:outputText value="#{cliente.cpf}" />
					</p:column>

					<p:column headerText="Telefone Residencial">
						<h:outputText value="#{cliente.endereco.telefoneResidencial}" />
					</p:column>

					<p:column headerText="Celular">
						<h:outputText value="#{cliente.endereco.celular}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{clientesBean.remover(cliente.id)}"
							update="cliente-datatable" />

						<p:commandButton value="Editar"
							action="#{clientesBean.carregar(cliente.id)}"
							oncomplete="PF('panel-cliente-form').show();"
							update="cliente-form" />
					</p:column>

				</p:dataTable>

			</p:panel>
		</h:form>

		<p:panel header="Dados do cliente" widgetVar="panel-cliente-form"
			closable="true" visible="false">

			<h:form prependId="false" id="cliente-form">

				<p:wizard backLabel="Anterior" nextLabel="Próximo">

					<p:tab title="1. Dados Pessoais">
						<p:panel header="Dados pessoais">

							<p:panelGrid columns="2" columnClasses="label,value"
								styleClass="grid">

								<h:outputLabel value="Nome" />
								<p:inputText label="Nome" value="#{clientesBean.cliente.nome}" />

								<h:outputLabel value="CPF" />
								<p:inputMask label="CPF" value="#{clientesBean.cliente.cpf}"
									mask="999.999.999-99" />

								<h:outputLabel value="RG" />
								<p:inputText label="RG" value="#{clientesBean.cliente.rg}" />

								<h:outputLabel value="Data de nascimento" />
								<p:calendar label="Data de nascimento"
									value="#{clientesBean.cliente.dataDeNascimento}"
									pattern="dd/MM/yyyy" navigator="true" yearRange="c-30:c+0">

									<f:convertDateTime pattern="dd/MM/yyyy" />
								</p:calendar>

								<h:outputText value="Sexo: " />
								<p:selectOneRadio label="Sexo"
									value="#{clientesBean.cliente.sexo}">
									<f:selectItems value="#{clientesBean.sexos}" var="sexo"
										itemLabel="#{sexo}" itemValue="#{sexo}" />
								</p:selectOneRadio>

								<h:outputText value="Estado Civil: " />
								<p:selectOneListbox label="Estado civil"
									value="#{clientesBean.cliente.estadoCivil}">
									<f:selectItems value="#{clientesBean.estadosCivis}"
										var="estadoCivil" itemLabel="#{estadoCivil}"
										itemValue="#{estadoCivil}" />
								</p:selectOneListbox>
							</p:panelGrid>
						</p:panel>

					</p:tab>

					<p:tab title="2. Endereço e contatos">
						<p:panel header="Endereço e contatos">

							<p:panelGrid columns="2" columnClasses="label,value"
								styleClass="grid">
								<h:outputLabel value="Logradouro" />
								<p:inputText value="#{clientesBean.cliente.endereco.logradouro}"
									label="Logradouro" />

								<h:outputLabel value="Número" />
								<p:inputText value="#{clientesBean.cliente.endereco.numero}"
									label="Número" />

								<h:outputLabel value="Complemento" />
								<p:inputText
									value="#{clientesBean.cliente.endereco.complemento}"
									label="Complemento" />

								<h:outputLabel value="Bairro" />
								<p:inputText value="#{clientesBean.cliente.endereco.bairro}"
									label="Bairro" />

								<h:outputLabel value="Cidade" />
								<p:inputText value="#{clientesBean.cliente.endereco.cidade}"
									label="Cidade" />

								<h:outputLabel value="Email" />
								<p:inputText value="#{clientesBean.cliente.endereco.email}"
									label="Email" />

								<h:outputLabel value="Telefone residencial" />
								<p:inputMask
									value="#{clientesBean.cliente.endereco.telefoneResidencial}"
									mask="(99) 9999-9999" label="Telefone residencial" />

								<h:outputLabel value="Celular" />
								<p:inputMask mask="(99) 9999-9999?9" label="Celular"
									value="#{clientesBean.cliente.endereco.celular}" />
							</p:panelGrid>
						</p:panel>

						<p:panel>
							<p:commandButton value="Cadastrar"
								action="#{clientesBean.salvar}"
								update="cliente-datatable,cliente-form"
								oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-cliente-form');"
								icon="ui-icon-circle-plus" rendered="#{!clientesBean.editar}" />

							<p:commandButton value="Atualizar"
								action="#{clientesBean.atualizar}"
								update="cliente-datatable,cliente-form"
								oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-cliente-form');"
								icon="ui-icon-circle-plus" rendered="#{clientesBean.editar}" />
						</p:panel>
					</p:tab>
				</p:wizard>
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/funcionario/gerenciarDiretores.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">
			<p:panel header="Diretores Cadastrados">

				<p:commandButton value="Cadastrar diretores"
					action="#{diretorBean.limpar()}" update="diretor-form"
					oncomplete="PF('panel-diretor-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />
                                
				<p:dataTable id="diretor-datatable" var="diretor"
					value="#{diretorBean.all}"
					filteredValue="#{diretorBean.diretoresFiltrados}"
					emptyMessage="Nenhum registro encontrado.">

					<p:column filterBy="#{diretor.nome}" headerText="Nome">
						<h:outputText value="#{diretor.nome}" />
					</p:column>

					<p:column headerText="Ganhador de Oscar">
						<h:outputText value="#{diretor.ganhadorDoOscar ? 'Sim' : 'Não'}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{diretorBean.remover(diretor.id)}"
							update="diretor-datatable" />

						<p:commandButton value="Editar"
							action="#{diretorBean.carregar(diretor.id)}"
							oncomplete="PF('panel-diretor-form').show();"
							update="diretor-form" />
					</p:column>

				</p:dataTable>
			</p:panel>
		</h:form>

		<p:panel header="Dados do Diretor" widgetVar="panel-diretor-form"
			closable="true" visible="false">

			<h:form prependId="false" id="diretor-form">

				<p:panel>
					<h:panelGrid columns="2" columnClasses="label,value"
						styleClass="grid">

						<h:outputText value="Nome *" />
						<p:inputText label="Nome" value="#{diretorBean.diretor.nome}" />

						<h:outputText value="Ganhador de Oscar: *" />
						<p:selectBooleanCheckbox value="#{diretorBean.diretor.ganhadorDoOscar}" />

					</h:panelGrid>
				</p:panel>

				<p:panel>
					<p:commandButton value="Cadastrar" action="#{diretorBean.salvar}"
						update="diretor-datatable,diretor-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-diretor-form');"
						icon="ui-icon-circle-plus" rendered="#{!diretorBean.editar}" />

					<p:commandButton value="Atualizar"
						action="#{diretorBean.atualizar}"
						update="diretor-datatable,diretor-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-diretor-form');"
						icon="ui-icon-circle-plus" rendered="#{diretorBean.editar}" />
				</p:panel>
			</h:form>
		</p:panel>

	</ui:define>
</ui:composition>
</html>

src/main/webapp/funcionario/gerenciarFilmes.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">

			<p:panel header="Filmes cadastrados">

				<p:commandButton value="Cadastrar filme"
					action="#{filmesBean.limpar()}" update="filme-form"
					oncomplete="PF('panel-filme-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />

				<p:dataTable id="filme-datatable" var="filme"
					value="#{filmesBean.all}"
					filteredValue="#{filmesBean.filmesFiltrados}"
					emptyMessage="Nenhum registro encontrado.">


					<p:column headerText="Título" filterBy="#{filme.titulo}">
						<h:outputText value="#{filme.titulo}" />
					</p:column>

					<p:column headerText="Ano" filterBy="#{filme.ano}">
						<h:outputText value="#{filme.ano}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{filmesBean.remover(filme.id)}" update="filme-datatable" />

						<p:commandButton value="Editar"
							action="#{filmesBean.carregar(filme.id)}"
							oncomplete="PF('panel-filme-form').show();" update="filme-form" />
					</p:column>

				</p:dataTable>


			</p:panel>
		</h:form>

		<p:panel header="Dados do Filme" widgetVar="panel-filme-form"
			closable="true" visible="false">

			<h:form prependId="false" id="filme-form">

				<p:panel>
					<p:panelGrid columns="2" columnClasses="label,value"
						styleClass="grid">

						<h:outputLabel value="Título" />
						<p:inputText value="#{filmesBean.filme.titulo}" label="Título" />

						<h:outputLabel value="Ano" />
						<p:inputMask mask="9999" value="#{filmesBean.filme.ano}"
							label="Ano" />

						<h:outputLabel value="Categoria" />
						<p:selectOneRadio label="Categoria"
							value="#{filmesBean.filme.categoria}"
							converter="categoriaConverter">
							<f:selectItems value="#{categoriaBean.all}" var="categoria"
								itemLabel="#{categoria.tipo}" itemValue="#{categoria}">
							</f:selectItems>
						</p:selectOneRadio>

						<h:outputLabel value="Diretor" />
						<p:autoComplete label="Diretor"
							value="#{filmesBean.filme.diretor}"
							completeMethod="#{diretorBean.completaDiretores}"
							converter="diretorConverter" var="diretor" itemValue="#{diretor}"
							itemLabel="#{diretor.nome}">
						</p:autoComplete>

						<h:outputLabel value="Ator" />
						<p:autoComplete label="Ator" value="#{filmesBean.filme.atores}"
							completeMethod="#{atoresBean.completaAtores}"
							converter="atorConverter" var="ator" itemValue="#{ator}"
							itemLabel="#{ator.nome}" multiple="true" />
					</p:panelGrid>
				</p:panel>
				<p:panel>
					<p:commandButton value="Cadastrar" action="#{filmesBean.salvar}"
						update="filme-datatable,filme-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-filme-form');"
						icon="ui-icon-circle-plus" rendered="#{!filmesBean.editar}" />

					<p:commandButton value="Atualizar" action="#{filmesBean.atualizar}"
						update="filme-datatable,filme-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-filme-form');"
						icon="ui-icon-circle-plus" rendered="#{filmesBean.editar}" />
				</p:panel>
			</h:form>
		</p:panel>

	</ui:define>
</ui:composition>
</html>

src/main/webapp/funcionario/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

	<ui:composition template="/template/defaultFuncionario.xhtml">
	
		<ui:define name="conteudo">
			
			
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/funcionario/reservarFilmes.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template/defaultFuncionario.xhtml">

	<ui:define name="conteudo">

		<h:form prependId="false">
			<p:growl autoUpdate="true" sticky="true" />
		</h:form>

		<h:form prependId="false">

			<p:panel header="Reservar de Filmes">

				<p:commandButton value="Nova reserva"
					action="#{reservasBean.limpar()}" update="reserva-form"
					oncomplete="PF('panel-reserva-form').show();"
					icon="ui-icon-circle-plus" class="botao-cadastro" />

				<p:dataTable id="reserva-datatable" var="reserva"
					value="#{reservasBean.all}"
					filteredValue="#{reservasBean.reservasFiltradas}"
					emptyMessage="Nenhum registro encontrado.">

					<p:column filterBy="#{reserva.cliente.nome}" headerText="Cliente">
						<h:outputText value="#{reserva.cliente.nome}" />
					</p:column>

					<p:column filterBy="#{reserva.filme.titulo}" headerText="Filme">
						<h:outputText value="#{reserva.filme.titulo}" />
					</p:column>
					
					<p:column headerText="Horário">
						<h:outputText value="#{reserva.horario.toLocaleString()}" />
					</p:column>

					<p:column headerText="Ação">
						<p:commandButton value="Remover"
							action="#{reservasBean.remover(reserva.id)}"
							update="reserva-datatable" />

						<p:commandButton value="Editar"
							action="#{reservasBean.carregar(reserva.id)}"
							oncomplete="PF('panel-reserva-form').show();"
							update="reserva-form" />
					</p:column>

				</p:dataTable>


			</p:panel>
		</h:form>

		<p:panel header="Reservar Filme" widgetVar="panel-reserva-form"
			closable="true" visible="false">

			<h:form prependId="false" id="reserva-form">

				<p:panel>
					<p:panelGrid columns="2" columnClasses="label,value" styleClass="grid">

						<h:outputLabel value="Cliente" />
						<p:selectOneMenu value="#{reservasBean.reserva.cliente}"
							converter="clienteConverter" style="width:100%">
							<f:selectItems value="#{clientesBean.all}" var="cliente"
								itemLabel="#{cliente.nome}" itemValue="#{cliente}" />
						</p:selectOneMenu>

						<h:outputLabel value="Filme" />
						<p:selectOneMenu value="#{reservasBean.reserva.filme}"
							converter="filmeConverter" style="width:100%">
							<f:selectItems value="#{filmesBean.all}" var="filme"
								itemLabel="#{filme.titulo}" itemValue="#{filme}" />
						</p:selectOneMenu>
						
					</p:panelGrid>
				</p:panel>
				
				<p:panel>
					<p:commandButton value="Cadastrar" action="#{reservasBean.salvar}"
						update="reserva-datatable,reserva-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-reserva-form');"
						icon="ui-icon-circle-plus" rendered="#{!reservasBean.editar}" />

					<p:commandButton value="Atualizar"
						action="#{reservasBean.atualizar}"
						update="reserva-datatable,reserva-form"
						oncomplete="hidePanelOnSuccess(xhr, status, args, 'panel-reserva-form');"
						icon="ui-icon-circle-plus" rendered="#{reservasBean.editar}" />
				</p:panel>
			</h:form>
		</p:panel>

	</ui:define>
</ui:composition>
</html>